'use client';
import {useState} from 'react';
import {records,retrieveMemory,exclusion,type SearchMethod} from '@/lib/experiments';
import {Card,Choice,Intro,LabFooter,More,Stat,Range,Evidence,Steps,Takeaway,TypeChip} from './lab-parts';

const methods=[{id:'lexical',name:'Same words',hint:'Counts words shared with the question'},{id:'concept',name:'Related words',hint:'Also counts related words, like warm → temperature'},{id:'exact',name:'Exact field',hint:'Ignores the wording and reads one named field'}] as const;
const questions=['How warm do I like it?','What is my comfort temperature?','What should we do before the next heatwave?'];
const outcome={'Top K':'Over the memory limit','Word budget':'No room left'} as const;
export default function RetrieveLab(){
 const [query,setQuery]=useState(questions[0]),[method,setMethod]=useState<SearchMethod>('lexical'),[key,setKey]=useState('temperature'),[person,setPerson]=useState('Alex'),[k,setK]=useState(3),[budget,setBudget]=useState(80),[safe,setSafe]=useState(true);
 const result=retrieveMemory(records,query,key,method,person,'2026-09-26',k,budget,safe);
 const filtered=records.filter(r=>r.person!==person||(safe&&exclusion(r,person,'2026-09-26'))).length;
 return <><Intro title="Find only the memories that answer the question.">An assistant can’t read every memory on every turn. It searches, then copies the few best matches into its prompt. How it searches decides what it finds.</Intro>
 <Steps items={['With “Same words”, the 70°F memory is missed: “warm” never appears in it. Switch to “Related words” and it is found.','Drag “Room in the prompt” down to 10 words. Nothing fits, so the assistant should say it doesn’t know.','Open “More controls” and switch the person to Riley. Alex’s memories disappear; each person has their own.']}/>
 <div className="ml-controls ml-controls-wide"><label>Question<input value={query} maxLength={500} onChange={e=>setQuery(e.target.value)}/></label><div className="ml-presets" role="group" aria-label="Example questions">{questions.map(q=><button key={q} aria-pressed={query===q} onClick={()=>setQuery(q)}>{q}</button>)}</div></div>
 <Choice label="How to search" value={method} onChange={setMethod} options={methods}/>
 {method==='exact'&&<div className="ml-controls"><label>Field to read<select value={key} onChange={e=>setKey(e.target.value)}>{['temperature','fan','heatwave','helpdesk','parking','site'].map(x=><option key={x}>{x}</option>)}</select></label></div>}
 <div className="ml-controls ml-controls-two"><Range label="Most memories to include" value={k} min={1} max={6} onChange={setK}/><Range label="Room in the prompt (words)" value={budget} min={10} max={160} step={10} onChange={setBudget}/></div>
 <More summary="More controls"><div className="ml-controls"><label>Person<select value={person} onChange={e=>setPerson(e.target.value)}><option>Alex</option><option>Riley</option></select></label></div><label className="ml-check"><input type="checkbox" checked={safe} onChange={e=>setSafe(e.target.checked)}/>Leave out replaced, deleted, expired, future, and untrusted memories</label></More>
 <div className="ml-stats"><Stat label="Ruled out first" value={`${filtered} / ${records.length}`} note="Someone else’s, out of date, or untrusted"/><Stat label="Memories included" value={`${result.selected.length} / ${k}`}/><Stat label="Words used" value={`${result.used} / ${budget}`} note="Counted in words, not model tokens"/></div>
 <div className="ml-grid"><Card title="What the assistant gets"><div className="ml-budget" aria-hidden="true"><div style={{width:`${result.used/budget*100}%`}}/></div><pre className="ml-code">{result.selected.map(r=>`[${r.record.id}] ${r.record.value}\n${r.record.quote}`).join('\n\n')||'Nothing found. The assistant should say it doesn’t know rather than invent a memory.'}</pre>{result.selected.map(r=><Evidence key={r.record.id} record={r.record}/>)}</Card>
 <Card title="How each memory scored"><div className="ml-table"><table><caption>Score = matching words. Best first; ties go to the lower ID.</caption><thead><tr><th>Memory</th><th>Score</th><th>Result</th></tr></thead><tbody>{result.ranked.map(r=>{const why=result.skipped.find(x=>x.id===r.record.id)?.why;return <tr key={r.record.id}><td>{r.record.id} <TypeChip kind={r.record.kind}/></td><td>{r.score}</td><td>{why?outcome[why as keyof typeof outcome]??why:'Included'}</td></tr>;})}</tbody></table></div>{!result.ranked.length&&<p>No matches. Try another question or “Related words”.</p>}<p>Memories go in best-first until the limit or the room runs out. One that is too long is skipped, so a shorter one further down can still fit.</p></Card></div>
 <details className="ml-all"><summary>See all 12 memories and why each is in or out</summary>{records.map(r=><div key={r.id}><p>{r.id}: {r.person!==person?'Someone else’s':safe?exclusion(r,person,'2026-09-26')??'Can be used':'Filters switched off'}</p><Evidence record={r}/></div>)}</details>
 <Takeaway>search on meaning, not just matching words, and include a few strong memories rather than many weak ones. When nothing relevant fits, “I don’t know” is the right answer.</Takeaway>
 <LabFooter real="search uses learned embeddings rather than our four hand-written word groups, and long conversations are trimmed, summarized, or moved out and retrieved when needed. Summaries can drop qualifiers: “70°F for today’s workshop” must not quietly become “always prefers 70°F,” so keep the source and date with each memory." note="No model reads this evidence. The lab shows only the choosing step that comes before an answer is written." section="retrieve"/></>;
}
