'use client';
import {useState} from 'react';
import {candidates,commitWrite,initialWrite} from '@/lib/experiments';
import {Card,Choice,Intro,LabFooter,More,Stat,Steps,Takeaway,TypeChip} from './lab-parts';

export default function WriteLab(){
 const [state,setState]=useState(initialWrite),[choice,setChoice]=useState('0'),[base,setBase]=useState(1),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState('');
 const candidate=candidates[+choice];
 function select(i:string){setChoice(i);setReviewed(false);setMessage('');}
 function save(){try{const next=commitWrite(state,candidate.value,candidate.source,candidate.date,base);setState(next);setBase(next.revision);setMessage(next===state?'Already saved, so nothing changed.':'Saved. The old value stays in the history.');}catch(e){setMessage((e as Error).message);}}
 return <><Intro title="Not every message should become a memory.">Alex’s saved comfort temperature is 73°F. Four messages each suggest a change. Pick one, read where it came from, and decide whether it should be saved.</Intro>
 <Steps items={['Pick “A correction”, tick the check box and save. 70°F becomes current and 73°F moves to the history.','Pick “A one-off event” or “A suspicious note”. Saving is blocked: neither is Alex’s own preference.','Open “What if two people edit at once?” to see why a save can be refused.']}/>
 <div className="ml-grid"><Card title="Choose a message"><Choice label="Message" value={choice} onChange={select} options={candidates.map((c,i)=>({id:String(i),name:c.label,hint:`Suggests: ${c.value}`}))}/><blockquote>{candidate.quote}</blockquote><p className="ml-source">{candidate.source} · {candidate.date}</p><p>{candidate.why}</p><label className="ml-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I checked this against its source</label><div className="ml-actions"><button disabled={!reviewed||candidate.decision==='reject'} onClick={save}>Save to memory</button><button onClick={()=>setMessage('Not saved. The memory is unchanged.')}>Don’t save</button></div>{message&&<p role="status" className="ml-note">{message}</p>}</Card>
 <Card title="Alex’s saved comfort temperature"><p><TypeChip kind="semantic"/> A fact about Alex, kept across conversations.</p><Stat label="Current value" value={state.value} note={`${state.source} · ${state.date}`}/><ol className="ml-timeline">{state.history.map(h=><li key={h.revision}><span>v{h.revision} · replaced</span><strong>{h.value}</strong><small>{h.source} · {h.date}</small></li>)}<li><span>v{state.revision} · current</span><strong>{state.value}</strong><small>What the assistant would use today</small></li></ol></Card></div>
 <More summary="What if two people edit at once?"><p>You read version {base}. If someone else saves first, the memory moves on to a newer version, and saving yours would quietly undo their change. So your save is refused until you re-read the latest version.</p><div className="ml-actions"><button onClick={()=>{setState(s=>({...s,revision:s.revision+1}));setMessage('Someone else saved a newer version. Re-read it before saving yours.');}}>Simulate someone else saving</button><button onClick={()=>{setBase(state.revision);setReviewed(false);setMessage('You now have the latest version. Check the message again.');}}>Re-read latest version</button></div><p className="ml-define">Current version: {state.revision}. Your change is based on version {base}.</p></More>
 <Takeaway>save a memory only after checking where it came from. A correction replaces the old value but keeps it in the history. Repeats, one-off events, and notes that give themselves orders change nothing.</Takeaway>
 <LabFooter real="saving while the assistant replies makes a memory available at once but slows the reply. Saving later, in the background, keeps replies fast, but another conversation may briefly see the old version. Either way you need rules for corrections and duplicates." note="The four messages and their verdicts are hand-written; nothing is extracted from text automatically. A newer message is not automatically more true." section="write"/></>;
}
