'use client';
import {useState} from 'react';
import {cases,records,evaluateMode,experimentVersion,exportJson,parseMeasurement,retrievalMetrics,type MeasuredRun} from '@/lib/experiments';
import {Card,Intro,LabFooter,More,Stat,Range,Bar,Evidence,Steps,Takeaway,percent} from './lab-parts';

export default function EvaluateLab(){
 const [k,setK]=useState(3),[budget,setBudget]=useState(80),[selected,setSelected]=useState('correction'),[run,setRun]=useState<MeasuredRun|null>(null),[error,setError]=useState(''),[verdicts,setVerdicts]=useState<Record<string,string>>({});
 const modes=[{id:'off' as const,label:'Memory off'},{id:'all' as const,label:'Every memory'},{id:'filtered' as const,label:'Relevant, current memories'}];
 const results=modes.map(m=>({...m,rows:evaluateMode(m.id,k,budget)}));
 const current=cases.find(c=>c.id===selected)!;
 const imported=run?.results.find(r=>r.caseId===selected);
 const reviewed=Object.values(verdicts).filter(Boolean),supported=reviewed.filter(v=>v==='supported').length;
 function kit(){exportJson('memory-evaluation-kit.json',{dataset:experimentVersion,provenance:'Authored fictional records and expected answers, not independent labels',records,cases,measurementSchema:{schema:'memory-lab-run-v1',dataset:experimentVersion,name:'Your run',model:'Exact model and revision',environment:'Record date, hardware, prompts, tokenizer, warm-ups, cache state, and timing/cost boundaries',results:cases.map(c=>({caseId:c.id,ids:[],answer:'Actual answer',latencyMs:'Measured milliseconds',inputTokens:'Actual integer',outputTokens:'Actual integer',costUsd:null}))}});}
 return <><Intro title="Does memory make answers better?">Six questions about Alex and Riley, answered three ways: with memory off, with every memory, and with only the relevant, current ones. Green is a right answer, including “I don’t know” when nothing answers the question.</Intro>
 <Steps items={['Compare the three scores. Memory off knows almost nothing, and every memory still gets Alex’s temperature wrong.','Click the red “Wrong” in the Every memory column. It answered 73°F, Alex’s old setting, because the out-of-date memory came first.','Open “Change the limits” and set the memory limit to 1. Now the relevant-only approach starts failing too: too little context also hurts.']}/>
  <div className="ml-stats">{results.map(m=><Stat key={m.id} label={m.label} value={`${m.rows.filter(r=>r.correct).length} / ${cases.length}`} note="Right answers"/>)}</div>
 <More summary="Change the limits"><p>These apply to the relevant-only approach, as in the Find lab.</p><div className="ml-controls ml-controls-two"><Range label="Most memories to include" min={1} max={6} value={k} onChange={setK}/><Range label="Room in the prompt (words)" min={10} max={160} step={10} value={budget} onChange={setBudget}/></div></More>
 <Card title="Six questions, three approaches"><div className="ml-table"><table><caption>Click any cell to see why. “Out of date” counts replaced, expired, or deleted memories that reached the answer.</caption><thead><tr><th>Question</th>{modes.map(m=><th key={m.id}>{m.label}</th>)}</tr></thead><tbody>{cases.map(c=><tr key={c.id}><th>{c.question}<small>{c.person}</small></th>{results.map(m=>{const r=m.rows.find(x=>x.caseId===c.id)!;return <td key={m.id}><button className={`ml-cell ${r.correct?'match':'miss'}`} onClick={()=>setSelected(c.id)} aria-label={`${c.id}, ${m.label}, ${r.correct?'right':'wrong'}`}>{r.correct?'Right':'Wrong'}<small>{r.ids.length} {r.ids.length===1?'memory':'memories'} · {r.stale} out of date</small></button></td>;})}</tr>)}</tbody></table></div></Card>
 <Card title="Why this answer?"><label>Question<select value={selected} onChange={e=>setSelected(e.target.value)}>{cases.map(c=><option key={c.id} value={c.id}>{c.question} ({c.person})</option>)}</select></label><p>Expected: <strong>{current.expected??'“I don’t know”: no memory answers this'}</strong>. {current.reason}</p>{results.map(m=>{const r=m.rows.find(x=>x.caseId===selected)!;return <article className="ml-result" key={m.id}><strong>{m.label}: {r.answer??'I don’t know'}</strong><p>Memories used: {r.ids.join(', ')||'none'}</p><Bar label="Precision" value={r.precision}/><Bar label="Recall" value={r.recall}/></article>;})}<p><strong>Precision</strong> asks: of the memories it used, how many were the right ones? <strong>Recall</strong> asks: of the right memories, how many did it use? Either shows N/A when there is nothing to divide by.</p>{current.targets.map(id=><Evidence key={id} record={records.find(r=>r.id===id)!}/>)}</Card>
 <Takeaway>more memory is not better memory. Handing over everything brings back outdated answers; choosing only relevant, current memories fixes that, until the limit is so small the answer no longer fits.</Takeaway>
 <More summary="For developers: test your own model"><p>Nothing here is measured. Export the kit, run your own model on the six questions, then import its answers and review each one by hand. No API key or model call is made here.</p><div className="ml-actions"><button onClick={kit}>Export evaluation kit</button><button onClick={()=>exportJson('memory-local-evaluation.json',{dataset:experimentVersion,kind:'deterministic field reader',k,budget,results})}>Export local results</button></div><label>Import measured run<input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>200000)throw new Error('Keep runs under 200 KB.');setRun(parseMeasurement(await file.text()));setVerdicts({});setError('');}catch(err){setError((err as Error).message);}e.target.value='';}}/></label>{error&&<p role="alert">{error}</p>}<details><summary>What the import file must contain</summary><p>Exactly six results, one per question, each with the memory IDs used, the answer text, latency in milliseconds, whole-number input and output tokens, and a cost (or null). A bad file leaves the previous run in place. Six timings say nothing reliable about production speed, and imported numbers are not verified.</p></details>
 {run?<><h4>{run.name} · {run.model}</h4><p>{run.environment}</p><div className="ml-stats"><Stat label="Mean reported latency" value={`${(run.results.reduce((s,r)=>s+r.latencyMs,0)/cases.length).toFixed(1)} ms`}/><Stat label="Total reported cost" value={run.results.some(r=>r.costUsd===null)?'Unmeasured':`$${run.results.reduce((s,r)=>s+(r.costUsd??0),0).toFixed(6)}`}/><Stat label="Input / output tokens" value={`${run.results.reduce((s,r)=>s+r.inputTokens,0)} / ${run.results.reduce((s,r)=>s+r.outputTokens,0)}`}/></div>{imported&&<><h4>Imported answer · {current.question}</h4><blockquote>{imported.answer||'No answer supplied'}</blockquote><p>Memories used: {imported.ids.join(', ')||'none'} · Recall: {percent(retrievalMetrics(imported.ids,current.targets).recall)}</p>{imported.ids.map(id=><Evidence key={id} record={records.find(r=>r.id===id)!}/>)}<label>Manual answer assessment<select value={verdicts[selected]??''} onChange={e=>setVerdicts({...verdicts,[selected]:e.target.value})}><option value="">Not reviewed</option><option value="supported">Supported and complete / appropriate abstention</option><option value="unsupported">Unsupported statement</option><option value="stale">Uses stale information</option><option value="incomplete">Incomplete or incorrect</option></select></label></>}<p>{supported} acceptable / {reviewed.length} manually reviewed. Read every claim and its source; the app does not judge answers for you.</p><button onClick={()=>exportJson('memory-model-review.json',{dataset:experimentVersion,run,verdicts,provenance:'Manual assessments; not independently verified'})}>Export measured review</button></>:<p className="ml-empty">No model run imported yet.</p>}</More>
 <LabFooter note="A simple reader returns the first matching field or says it does not know; no model writes an answer. The six questions and their answers were written by us, so this is a demonstration, not a benchmark." section="evaluate"/></>;
}
