'use client';
import {useState} from 'react';
import {loadModel} from '@/lib/experiments';
import {Card,More,Stat,Range,Steps,percent} from './lab-parts';

// Lives in Design for scale, next to the traffic chart it puts to the test.
export default function QueueSimulator(){
 const [qps,setQps]=useState(10),[service,setService]=useState(200),[workers,setWorkers]=useState(2),[burst,setBurst]=useState(1),[deadline,setDeadline]=useState(800);
 const run=loadModel(qps,service,workers,burst,deadline),max=Math.max(deadline,...run.rows.map(r=>r.total));
 return <div className="memory-labs queue-lab"><Steps items={['Raise “Burst size” to 20. The average rate is unchanged, but the line climbs past the deadline.','Add workers until deadline misses return to 0.','Open “Exact request data” to check every simulated request behind the chart.']}/>
 <div className="ml-controls ml-controls-two"><Range label="Burst size" min={1} max={20} value={burst} onChange={setBurst}/><Range label="Workers" min={1} max={8} value={workers} onChange={setWorkers}/></div>
 <More summary="More controls: traffic, service time, and deadline"><div className="ml-controls"><Range label="Requests per second" min={5} max={50} step={5} value={qps} onChange={setQps}/><Range label="Service time ms" min={100} max={1000} step={100} value={service} onChange={setService}/><Range label="Deadline ms" min={200} max={3000} step={100} value={deadline} onChange={setDeadline}/></div></More>
 <div className="ml-stats four"><Stat label="Deadline misses" value={`${run.misses} / 60`} note="Late, but still answered"/><Stat label="p95 response time" value={`${run.p95.toFixed(0)} ms`} note="95 of 100 requests finish within this"/><Stat label="Requests arriving" value={`${qps}/s`} note={`Workers can serve up to ${run.capacity.toFixed(1)}/s`}/><Stat label="Workers busy" value={percent(run.utilization)} note="Share of time spent serving"/></div>
 <Card title="Watch the queue grow"><div className="ml-chart-scroll" tabIndex={0} role="region" aria-label="Scrollable latency chart"><svg className="ml-chart" viewBox="0 0 720 250" role="img" aria-label={`Simulated total response time. p95 ${run.p95.toFixed(0)} ms, ${run.misses} deadline misses. Exact values in the table below.`}><text x="55" y="20">Response time (ms)</text>{[0,.5,1].map(n=><g key={n}><line x1="55" x2="700" y1={210-n*170} y2={210-n*170} stroke="#365247"/><text x="48" y={215-n*170} textAnchor="end">{Math.round(n*max)}</text></g>)}<line x1="55" x2="700" y1={210-deadline/max*170} y2={210-deadline/max*170} stroke="#f4c48b" strokeDasharray="6 4"/><polyline points={run.rows.map((r,i)=>`${55+i/59*645},${210-r.total/max*170}`).join(' ')} fill="none" stroke="#bcebc6" strokeWidth="3"/><text x="55" y="239">Request 1</text><text x="700" y="239" textAnchor="end">Request 60</text></svg></div><p>Solid line: time waiting plus time being served. Dashed line: the {deadline} ms deadline.</p><details><summary>Exact request data</summary><div className="ml-table"><table><thead><tr><th>Request</th><th>Arrival ms</th><th>Wait ms</th><th>Total ms</th><th>Deadline</th></tr></thead><tbody>{run.rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.arrival.toFixed(1)}</td><td>{r.wait.toFixed(1)}</td><td>{r.total.toFixed(1)}</td><td>{r.miss?'Missed':'Met'}</td></tr>)}</tbody></table></div></details></Card></div>;
}
