export type MemoryId = "working" | "short" | "semantic" | "episodic" | "procedural";
export type MemoryKind = { id: MemoryId; name: string; tag: string; description: string; analogy: string; scenario: string; prompt: string; seed: string[]; contains: string; implementation: string; lesson: string; without: string; color: string };

export const kinds: MemoryKind[] = [
  { id: "working", name: "Working memory", tag: "THE SCRATCHPAD", description: "Holds the information an agent needs to finish the task in front of it.", analogy: "The checklist on a facilities manager’s clipboard during a job.", scenario: "Get a floor ready for an evening event", prompt: "Set up the building for tonight’s town hall.", seed: ["Space: Riverside Tower, Level 12", "Event time: 6–9 p.m., 120 people", "Keep lights and air on until: 9:30 p.m."], contains: "The details of the job in hand", implementation: "A task-state object holding constraints and intermediate results.", lesson: "Working memory is what the agent is juggling right now: the facts for this one job. In CoALA it holds the information needed for the current decision. In practice it often lives inside the conversation, so the two overlap.", without: "Which floor or room, what time, and how many people should the building be ready for?", color: "mint" },
  { id: "short", name: "Short-term memory", tag: "THE CONVERSATION", description: "Keeps recent messages in context so a conversation can flow naturally.", analogy: "Remembering what a caller to the helpdesk said a moment ago.", scenario: "Fix a stuffy meeting room", prompt: "Okay, go with the other option then.", seed: ["You: Meeting room 3B feels stuffy every afternoon.", "Assistant: I can bring in more fresh air or lower the temperature by 2°F.", "You: Please don’t make it colder. People by the window already feel chilly."], contains: "The conversation so far", implementation: "An ordered message history, often trimmed or summarized to fit a context window.", lesson: "Short-term memory is the conversation so far. It lets “the other option” make sense. Context windows are limited, so long conversations get trimmed or summarized. Start a new chat and it is gone.", without: "Which options do you mean? Tell me the room and what you’d like changed, and I can help.", color: "blue" },
  { id: "semantic", name: "Semantic memory", tag: "THE KNOWLEDGE", description: "Remembers facts and preferences beyond a single conversation.", analogy: "Knowing a colleague always feels cold near the window.", scenario: "A workplace assistant that knows you", prompt: "Get my workspace ready for tomorrow.", seed: ["Comfort temperature: 70°F", "Usual workspace: Riverside Tower, Level 4", "Prefers: a quiet desk by the window"], contains: "Facts and preferences", implementation: "A user profile or collection of facts in a database; retrieval may use exact lookup or search.", lesson: "Semantic memory is what the agent knows about the world and about you. It lasts across conversations, so it must be correctable: edit the temperature and run again. “Semantic” describes the content, not a search technique.", without: "I can book a desk and set the zone temperature. Which building and floor, and what temperature do you prefer?", color: "violet" },
  { id: "episodic", name: "Episodic memory", tag: "THE EXPERIENCE", description: "Recalls specific past events and their outcomes to inform the next decision.", analogy: "Remembering what happened the last time the chiller failed.", scenario: "Learn from last summer’s heatwave", prompt: "Help me prepare the building for next week’s heatwave.", seed: ["Jul 14 · Heatwave: Level 9 reached 82°F by 3 p.m.", "Outcome: chiller CH-2 tripped on high load and meetings moved.", "Lesson from that event: start pre-cooling at 5 a.m."], contains: "Past events and how they turned out", implementation: "Event records with time, context, action, and outcome, retrieved when relevant.", lesson: "Episodic memory is a record of something that happened and how it turned out. Agents can retrieve past episodes and draw lessons from them. A lesson that proves reliable can graduate into a fact or a procedure.", without: "Check the forecast, confirm the chillers have been serviced, and ask occupants to close blinds on sunny sides of the building.", color: "amber" },
  { id: "procedural", name: "Procedural memory", tag: "THE PLAYBOOK", description: "Stores reusable instructions for how an agent should carry out a task.", analogy: "The security team’s routine for locking up the building each night.", scenario: "A consistent facilities helpdesk", prompt: "The lights in my meeting room won’t turn on. Can you help?", seed: ["First, acknowledge the occupant’s problem.", "Then, ask for the room number and floor.", "Give one troubleshooting step at a time.", "If unresolved, raise a work order for the facilities team."], contains: "How-to steps and rules", implementation: "Versioned instructions, prompts, or reusable workflows loaded before acting.", lesson: "Procedural memory is how the agent does things. Research counts both the model’s trained skills and its written instructions; this demo shows only the written playbook. Editing it changes behavior without retraining anything, so only trusted people should be able to edit it.", without: "Try the wall switch, wave at the occupancy sensor, check the lighting panel, check the breaker, and contact facilities.", color: "rose" },
];

export type MemoryStore = Record<MemoryId, string[]>;

// Earlier starter records (everyday examples, then Celsius building examples). Browsers that saved them untouched get the current starters instead; edited records are kept.
const retiredSeeds: Partial<Record<MemoryId, string[][]>> = {
  semantic: [["Favorite drink: oat milk latte", "Preference: no added sugar", "Usually orders: a small"], ["Comfort temperature: 21°C", "Usual workspace: Riverside Tower, Level 4", "Prefers: a quiet desk by the window"]],
  episodic: [["May 12 · Trail hike: it rained unexpectedly.", "Outcome: shoes and spare clothes got soaked.", "Lesson from that trip: pack a waterproof bag."], ["Jul 14 · Heatwave: Level 9 reached 28°C by 3 p.m.", "Outcome: chiller CH-2 tripped on high load and meetings moved.", "Lesson from that event: start pre-cooling at 5 a.m."]],
  procedural: [["First, acknowledge the customer’s problem.", "Then, ask for their device model.", "Give one troubleshooting step at a time.", "If unresolved, offer escalation to a human."]],
};
export const upgradeRetiredSeed = (id: MemoryId, records: string[]): string[] => {
  const retired = retiredSeeds[id]?.some(seed => records.length === seed.length && records.every((r, i) => r === seed[i]));
  return retired ? [...kinds.find(k => k.id === id)!.seed] : records;
};
export const initialMemory = (): MemoryStore => Object.fromEntries(kinds.map(k => [k.id, [...k.seed]])) as MemoryStore;
export const isPersistent = (id: MemoryId) => ["semantic", "episodic", "procedural"].includes(id);
export const lifetimeLabel = (id: MemoryId) => isPersistent(id) ? "Saved in this browser" : "Cleared by a new chat";
export const countLabel = (n: number) => `${n} ${n === 1 ? "memory" : "memories"}`;

// Deliberately deterministic: show exactly what information reaches the response.
export function simulate(id: MemoryId, records: string[], enabled: boolean): string {
  const kind = kinds.find(k => k.id === id)!;
  if (!enabled || records.length === 0) return kind.without;
  switch (id) {
    case "working": return `Here’s the task brief I’ll plan around:\n${records.join("\n")}\n\nI’d schedule a lighting and air-conditioning override for the event window, pre-cool the floor for the headcount, and let the normal after-hours setback resume once it ends. These active constraints shape the plan.`;
    case "short": return `Here’s the conversation available as context:\n${records.join("\n")}\n\nA model could use these messages to resolve “the other option” and your constraints. This template echoes the history; it does not change any settings or interpret edited messages.`;
    case "semantic": return `I’ll use your saved workplace preferences:\n${records.join("\n")}\n\nYour desk booking and zone settings can follow this profile even in a new conversation. Update a fact if your preferences change.`;
    case "episodic": return `Last summer’s heatwave gives us useful context:\n${records.join("\n")}\n\nUse that experience alongside the standard heatwave checks. An event and its outcome help inform the next one.`;
    case "procedural": return `Here is the supplied helpdesk playbook:\n${records.map((r, i) => `${i + 1}. ${r}`).join("\n")}\n\nThis template displays the steps without executing them. A real agent would need to interpret the instructions, check permissions, and verify what actually happened.`;
  }
}
